// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce1.Models
{
    [Table("Color")]
    public partial class Color
    {
        public Color()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string Color_name { get; set; }

        [ForeignKey("Color_id")]
        [InverseProperty("Colors")]
        public virtual ICollection<Product> Products { get; set; }
    }
}