// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce1.Models
{
    [Table("Discount")]
    public partial class Discount
    {
        public Discount()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string Discount_name { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? Discount_percent { get; set; }
        public bool? Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Modified_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Deleted_at { get; set; }

        [InverseProperty("Discount")]
        public virtual ICollection<Product> Products { get; set; }
    }
}