// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce1.Models
{
    [Table("Product_Category")]
    public partial class Product_Category
    {
        public Product_Category()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(100)]
        public string Category_name { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Product> Products { get; set; }
    }
}