// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce1.Models
{
    [Table("Product")]
    public partial class Product
    {
        public Product()
        {
            Colors = new HashSet<Color>();
            Sizes = new HashSet<Size>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? Price { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created_at { get; set; }
        public int? Category_id { get; set; }
        public int? Inventory_id { get; set; }
        public int? Discount_id { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }

        [ForeignKey("Category_id")]
        [InverseProperty("Products")]
        public virtual Product_Category Category { get; set; }
        [ForeignKey("Discount_id")]
        [InverseProperty("Products")]
        public virtual Discount Discount { get; set; }
        [ForeignKey("Inventory_id")]
        [InverseProperty("Products")]
        public virtual Product_Inventory Inventory { get; set; }

        [ForeignKey("Product_id")]
        [InverseProperty("Products")]
        public virtual ICollection<Color> Colors { get; set; }
        [ForeignKey("Product_id")]
        [InverseProperty("Products")]
        public virtual ICollection<Size> Sizes { get; set; }
    }
}