// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce1.Models
{
    [Table("Product_Inventory")]
    public partial class Product_Inventory
    {
        public Product_Inventory()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int ID { get; set; }
        public int? Quantity { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Modified_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Deleted_at { get; set; }

        [InverseProperty("Inventory")]
        public virtual ICollection<Product> Products { get; set; }
    }
}