// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce1.Models
{
    [Table("Size")]
    public partial class Size
    {
        public Size()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string Size_name { get; set; }

        [ForeignKey("Size_id")]
        [InverseProperty("Sizes")]
        public virtual ICollection<Product> Products { get; set; }
    }
}